version: "3.9"

services:
  api:
    container_name: "network-share-api"

    image: node:16
    command: "yarn workspace @network-share/api start"
    ports:
      - "3030:3030"
    expose:
      - 3030
    volumes:
      - .:/srv/api
    env_file:
      - .env
    working_dir: /srv/api
    networks:
      - web
    environment:
      - NODE_ENV=production

  client:
    container_name: "network-share-client"
    image: node:16
    command: "yarn workspace @network-share/web start"
    ports:
      - "3000:3000"
    expose:
      - 3000
    volumes:
      - .:/srv/client
    working_dir: /srv/client
    depends_on:
      - api
    networks:
      - web
    env_file:
      - .env
    environment:
      - NODE_ENV=production

networks:
  web:
    external: true
