name: ESlint

on: [push, pull_request]

jobs:
  ESLint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
          node-version: ${{ matrix.node-version }}

      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@v3
        with:
          path: .turbo
          key: turbo-${{ github.job }}-${{ github.event.pull_request.head.ref }}-${{ github.event.pull_request.head.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.event.pull_request.head.ref }}-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run lint
        run: yarn lint
